### ISSUE TITLE
question on .toBe() semantic 

### ISSUE THREAD

**Issue by nippur72** [vsavkin/guinness#48]
Is it correct to assume that `toBe()` is implemented as `identical()` and not as normal Dart equality `==` ? 

I ask because I have a different result if compared to the Javascript counterpart:

```Dart
expect("a").toBe("a");  // PASS
expect("a"+"a").toBe("a"+"a");  // FAILs in Dart
```

**Comment by Pajn** [comment]
Yes, it's implemented using `identical()`. <https://github.com/vsavkin/guinness/blob/81fa9ee07f7255a7674b899675d4bc99c6db0f81/lib/src/common/unittest_backend.dart#L76-L77>

**Comment by nippur72** [comment]
ok, makes sense :)
